### PR TITLE
feat: support Vite 5

### PR DESCRIPTION
**Pull request by wyatt-herkamp**
It is not working on Legacy Browsers the tests for Legacy browser is failing. If you know how to fix this please help.

I did updated the other dependencies.

`@babel/preset-env` wanted a peer dependency of `@babel/core`

### CODE REVIEW

**Comment by aljazerzen** [comment]
@Menci Can this be merged.

FYI: legacy browser tests fail on my machine as well

**Comment by Menci** [comment]
Thanks. I'll check it soon.

**Comment by wyatt-herkamp** [comment]
I propose we have a new major release and drop Vite 2/3. And Node 14/16.

**Comment by Menci** [comment]
@aljazerzen @wyatt-herkamp Now everything should just work. Please check it and after then I'll merge and release it.

For the broken test, it's because the upgrade of `playwright`. I'm not sure it's the issue of playwright or corresponding version of Firefox that simulation of a legacy browser with `dom.moduleScripts.enabled` isn't working. Just pinning playwright's version does the fix.

**Comment by wyatt-herkamp** [comment]
Tested against my website it worked fine. Test Suite passed too.

**Pull request merged**
